# Generated by Django 5.2.7 on 2025-10-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Percentage', 'Percentage'), ('Specific', 'Specific'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('percentage_required', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
